// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atmdmvwlvvfnmbxtphjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bWRtdndsdnZmbm1ieHRwaGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzUwMDAsImV4cCI6MjA3MTY1MTAwMH0.p4eE5oMe0vnon0mXIZWe1MT9GCritrLyeJuqC7-9XmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});